[build]
publish = "."
functions = "functions"
command = "unzip -n hustlegen-mvp-secured.zip || true"

[[redirects]]
from = "/"
to = "/app"
status = 301

[[redirects]]
from = "/app/*"
to = "/app/index.html"
status = 200

[[headers]]
for = "/*"
  [headers.values]
  Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Permissions-Policy = "camera=(), microphone=(), geolocation=()"
  Content-Security-Policy = "default-src 'self'; script-src 'self'; object-src 'none'"

[[edge_functions]]
function = "firewall"
path = "/*"
