[build]
  publish = "."
  functions = "functions"
  command = "unzip -n hustlegen-mvp-secured.zip || true"

[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), usb=(), payment=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://challenges.cloudflare.com 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self' https://sentry.io; frame-src https://challenges.cloudflare.com https://js.stripe.com https://hooks.stripe.com; base-uri 'none'; form-action 'self'; frame-ancestors 'none'; upgrade-insecure-requests"

[[edge_functions]]
  function = "firewall"
  path = "/*"
